In [17]:
import pandas as pd
import numpy as np
import re

In [40]:
df=pd.read_csv("loan2.csv")
df

,id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate1,installment,grade,sub_grade,emp_title,...,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,application_type,pub_rec_bankruptcies
0,1,5000,5000,4975.00000,36 months,10.65,162.87,B,B2,NaN,...,5000.00,863.16,0.00,0.00,0.0000,15-Jan,171.62,17-Apr,INDIVIDUAL,0.0
1,2,2500,2500,2500.00000,60 months,15.27,59.83,C,C4,Ryder,...,456.46,435.17,0.00,122.90,1.1100,13-Apr,119.66,16-Oct,INDIVIDUAL,0.0
2,4,10000,10000,10000.00000,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,...,10000.00,2214.92,16.97,0.00,0.0000,15-Jan,357.48,16-Apr,INDIVIDUAL,0.0
3,5,3000,3000,3000.00000,60 months,12.69,67.79,B,B5,University Medical Group,...,3000.00,1066.91,0.00,0.00,0.0000,17-Jan,67.30,17-Jan,INDIVIDUAL,0.0
4,7,7000,7000,7000.00000,60 months,15.96,170.08,C,C5,Southern Star Photography,...,7000.00,3137.84,0.00,0.00,0.0000,16-May,1313.76,16-Sep,INDIVIDUAL,0.0
5,8,3000,3000,3000.00000,36 months,18.64,109.43,E,E1,MKC Accounting,...,3000.00,939.14,0.00,0.00,0.0000,15-Jan,111.34,14-Dec,INDIVIDUAL,0.0
6,9,5600,5600,5600.00000,60 months,21.28,152.39,F,F2,NaN,...,162.02,294.94,0.00,190.54,2.0900,12-Apr,152.39,16-Oct,INDIVIDUAL,0.0
7,10,5375,5375,5350.00000,60 months,12.69,121.45,B,B5,Starbucks,...,673.48,533.42,0.00,277.69,2.5200,12-Nov,121.45,16-Dec,INDIVIDUAL,0.0
8,11,6500,6500,6500.00000,60 months,14.65,153.45,C,C3,Southwest Rural metro,...,6500.00,1178.02,0.00,0.00,0.0000,13-Jun,1655.54,15-Dec,INDIVIDUAL,0.0
9,13,9000,9000,9000.00000,36 months,13.49,305.38,C,C1,Va. Dept of Conservation/Recreation,...,1256.14,570.26,0.00,450.92,4.1600,12-Jul,305.38,16-Oct,INDIVIDUAL,0.0
10,14,3000,3000,3000.00000,36 months,9.91,96.68,B,B1,Target,...,3000.00,480.27,0.00,0.00,0.0000,15-Jan,102.43,17-Apr,INDIVIDUAL,0.0
11,18,3600,3600,3600.00000,36 months,6.03,109.57,A,A1,Duracell,...,3600.00,185.27,0.00,0.00,0.0000,13-May,583.45,14-May,INDIVIDUAL,0.0
12,19,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,Connection Inspection,...,6000.00,1152.07,15.00,0.00,0.0000,15-Feb,16.98,15-Jul,INDIVIDUAL,0.0
13,21,20250,20250,19142.16108,60 months,15.27,484.63,C,C4,Archdiocese of Galveston Houston,...,20250.00,7429.05,0.00,0.00,0.0000,15-Aug,6024.09,16-Jun,INDIVIDUAL,0.0
14,22,21000,21000,21000.00000,36 months,12.42,701.73,B,B4,Osram Sylvania,...,10694.96,3330.44,0.00,9.20,0.0000,13-Sep,701.73,17-Feb,INDIVIDUAL,0.0
15,23,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,Value Air,...,10000.00,1907.35,0.00,0.00,0.0000,15-Jan,349.21,17-Apr,INDIVIDUAL,0.0
16,27,15000,15000,8725.00000,36 months,14.27,514.64,C,C2,nyc transit,...,0.00,0.00,0.00,0.00,0.0000,NaN,0.00,17-Apr,INDIVIDUAL,0.0
17,28,5000,5000,5000.00000,60 months,16.77,123.65,D,D2,Frito Lay,...,629.05,719.11,0.00,263.00,2.3000,12-Dec,123.65,16-Oct,INDIVIDUAL,0.0
18,30,8500,8500,8500.00000,36 months,11.71,281.15,B,B3,Oakridge homes,...,8500.00,1626.09,0.00,0.00,0.0000,14-Dec,581.59,15-Jan,INDIVIDUAL,0.0
19,31,4375,4375,4375.00000,36 months,7.51,136.11,A,A3,NaN,...,4375.00,524.96,0.00,0.00,0.0000,15-Jan,144.94,14-Dec,INDIVIDUAL,0.0
20,32,31825,31825,31825.00000,36 months,7.90,995.82,A,A4,Audubon Mutual Housing Corporation,...,31825.00,3061.91,0.00,0.00,0.0000,13-Aug,16966.70,16-Nov,INDIVIDUAL,0.0
21,34,5000,5000,5000.00000,36 months,8.90,158.77,A,A5,Good Samaritan Society,...,5000.00,715.56,0.00,0.00,0.0000,15-Jan,163.64,16-Dec,INDIVIDUAL,0.0
22,36,12400,12400,12400.00000,36 months,10.65,403.91,B,B2,Sharp Lawn Inc.,...,12400.00,2140.68,0.00,0.00,0.0000,15-Jan,417.61,17-Apr,INDIVIDUAL,0.0
23,37,10800,10800,10800.00000,36 months,9.91,348.03,B,B1,Department of Justice,...,10800.00,1359.19,0.00,0.00,0.0000,13-Nov,3483.79,16-Jan,INDIVIDUAL,0.0
24,38,15000,15000,15000.00000,36 months,7.90,469.36,A,A4,Gateway Hospice,...,15000.00,1663.34,0.00,0.00,0.0000,14-Jan,5872.80,16-Jun,INDIVIDUAL,0.0
25,39,6000,6000,6000.00000,36 months,12.42,200.50,B,B4,Cox Communications,...,6000.00,1127.72,0.00,0.00,0.0000,14-Apr,1923.53,17-Jan,INDIVIDUAL,0.0
26,40,12500,12500,12475.00000,60 months,12.69,282.44,B,B5,United States Infrastructure Corporation,...,12500.00,4445.88,0.00,0.00,0.0000,17-Jan,281.92,16-Dec,INDIVIDUAL,0.0
27,41,9600,9600,9600.00000,36 months,7.51,298.67,A,A3,Nucor Building Systems,...,9600.00,1151.87,0.00,0.00,0.0000,15-Jan,311.56,14-Dec,INDIVIDUAL,0.0
28,42,12000,12000,12000.00000,36 months,7.90,375.49,A,A4,John Wiley Jr.,...,12000.00,1517.36,0.00,0.00,0.0000,15-Jan,380.98,17-Apr,INDIVIDUAL,0.0
29,43,3000,3000,3000.00000,36 months,18.25,108.84,D,D5,NaN,...,3000.00,917.95,0.00,0.00,0.0000,15-Jan,115.38,17-Apr,INDIVIDUAL,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28988,42500,15600,8000,775.00000,36 months,11.86,265.17,D,D1,jenny craig weight loss,...,3074.52,1035.11,0.00,2067.08,372.0744,8-Nov,398.98,17-Apr,INDIVIDUAL,NaN
28989,42501,3500,3500,1025.00000,36 months,10.91,114.44,C,C3,Boston Architectural College,...,3500.00,609.50,30.00,0.00,0.0000,10-Mar,565.92,17-Jan,INDIVIDUAL,NaN
28990,42502,2600,2600,950.00000,36 months,14.38,89.35,E,E4,Department of Veterans Affairs,...,1159.26,446.30,0.00,202.20,70.7400,9-Jan,89.35,17-Feb,INDIVIDUAL,NaN
28991,42503,10500,4000,1150.00000,36 months,16.91,142.43,G,G2,"VUTEC, CORP",...,4000.00,1127.54,0.00,0.00,0.0000,10-Jul,143.43,10-Jul,INDIVIDUAL,NaN
28992,42504,10000,10000,1450.00000,36 months,10.59,325.46,C,C2,NaN,...,10000.00,717.46,0.00,0.00,0.0000,8-Apr,8114.58,16-Apr,INDIVIDUAL,NaN
28993,42505,20000,20000,700.00000,36 months,15.01,693.45,F,F1,hf palm corp,...,5191.34,2435.47,0.00,667.33,6.6800,8-Jun,693.44,9-Jan,INDIVIDUAL,NaN
28994,42506,6725,6725,825.00000,36 months,13.12,226.98,D,D5,MCHCP,...,3039.64,1171.30,0.00,0.09,0.0000,9-Apr,42.11,17-Apr,INDIVIDUAL,NaN
28995,42507,2000,2000,1025.00000,36 months,12.80,67.20,D,D4,Signs by Tomorrow,...,2000.00,419.12,0.00,0.00,0.0000,10-Jul,68.31,10-Jun,INDIVIDUAL,NaN
28996,42510,1900,1900,900.00000,36 months,9.64,61.00,B,B4,Scheduall,...,1900.00,99.14,0.00,0.00,0.0000,8-Feb,0.00,7-May,INDIVIDUAL,NaN
28997,42513,6000,6000,650.00000,36 months,10.59,195.28,C,C2,Yale University,...,6000.00,1029.87,0.00,0.00,0.0000,10-Jun,197.36,14-Oct,INDIVIDUAL,NaN
28998,42515,1200,1200,500.00000,36 months,9.01,38.17,B,B2,Classic Components,...,1200.00,173.99,0.00,0.00,0.0000,10-Jul,39.05,17-Apr,INDIVIDUAL,NaN
28999,42516,5000,5000,375.00000,36 months,11.22,164.23,C,C4,Compensation Solutions,...,5000.00,828.47,30.00,0.00,0.0000,10-Apr,149.43,17-Jan,INDIVIDUAL,NaN
29000,42517,1400,1400,475.00000,36 months,10.91,45.78,C,C3,"Stanford University Libraries, LOCKSS Project",...,1400.00,248.24,15.00,0.00,0.0000,10-Jul,1.78,14-Sep,INDIVIDUAL,NaN
29001,42518,1000,1000,625.00000,36 months,14.07,34.21,E,E3,Macy's,...,1000.00,231.57,0.00,0.00,0.0000,10-Jun,35.27,10-Jun,INDIVIDUAL,NaN
29002,42519,5000,5000,300.00000,36 months,7.75,156.11,A,A3,Diamond Management and Technology Consultants,...,5000.00,565.73,0.00,0.00,0.0000,9-Aug,1663.91,9-Aug,INDIVIDUAL,NaN
29003,42520,2500,2500,225.00000,36 months,7.43,77.69,A,A2,U.S. Bank,...,2500.00,100.24,0.00,0.00,0.0000,8-Jan,0.00,7-Jun,INDIVIDUAL,NaN
29004,42521,3000,3000,250.00000,36 months,7.43,93.23,A,A2,NC,...,3000.00,120.28,0.00,0.00,0.0000,8-Jan,0.00,7-Jun,INDIVIDUAL,NaN
29005,42522,2600,2600,575.00000,36 months,8.38,81.94,A,A5,College Pro Painters,...,1962.69,329.05,21.64,28.70,0.3400,10-Mar,21.75,16-Oct,INDIVIDUAL,NaN
29006,42523,1000,1000,625.00000,36 months,7.12,30.94,A,A1,Mana Products,...,1000.00,113.50,0.00,0.00,0.0000,10-Jun,32.93,14-Apr,INDIVIDUAL,NaN
29007,42524,6450,6450,0.00000,36 months,11.22,211.85,C,C4,Apto Solutions,...,6450.00,1228.62,120.00,0.00,0.0000,10-Jul,167.78,10-Jun,INDIVIDUAL,NaN
29008,42526,10500,10500,275.00000,36 months,11.22,344.87,C,C4,Town of Plainville,...,10500.00,719.85,0.00,0.00,0.0000,8-Aug,0.00,7-Jun,INDIVIDUAL,NaN
29009,42527,3000,3000,125.00000,36 months,9.01,95.42,B,B2,Tanks Tavern,...,3000.00,435.00,0.00,0.00,0.0000,10-Jul,95.66,10-Jun,INDIVIDUAL,NaN
29010,42528,3000,3000,0.00000,36 months,9.33,95.86,B,B3,NaN,...,3000.00,450.91,0.00,0.00,0.0000,10-Jun,96.77,7-May,INDIVIDUAL,NaN
29011,42529,2000,2000,225.00000,36 months,9.96,64.50,B,B5,NaN,...,2000.00,322.41,0.00,0.00,0.0000,10-Jul,0.84,10-Jul,INDIVIDUAL,NaN
29012,42530,6500,6500,0.00000,36 months,9.64,208.66,B,B4,Air Force,...,1791.32,503.81,0.00,4897.93,1714.2700,8-May,208.65,17-Apr,INDIVIDUAL,NaN
29013,42531,3500,3500,225.00000,36 months,10.28,113.39,C,C1,NaN,...,3500.00,219.43,0.00,0.00,0.0000,8-Mar,0.00,13-Feb,INDIVIDUAL,NaN
29014,42532,1000,1000,0.00000,36 months,9.64,32.11,B,B4,Halping hands company inc.,...,1000.00,155.60,0.00,0.00,0.0000,10-Jun,32.41,14-Sep,INDIVIDUAL,NaN
29015,42533,2525,2525,225.00000,36 months,9.33,80.69,B,B3,NaN,...,2525.00,379.50,0.00,0.00,0.0000,10-Jun,82.03,7-May,INDIVIDUAL,NaN
29016,42534,6500,6500,0.00000,36 months,8.38,204.84,A,A5,NaN,...,6500.00,873.90,0.00,0.00,0.0000,10-Jun,205.32,7-Aug,INDIVIDUAL,NaN
29017,42535,5000,5000,0.00000,36 months,7.75,156.11,A,A3,Homemaker,...,5000.00,619.76,0.00,0.00,0.0000,10-Jun,156.39,15-Feb,INDIVIDUAL,NaN

In [41]:
type(df['emp_length'])

pandas.core.series.Series

In [50]:
pattern=r'\d+'
emp_length2=[]
for value in df['emp_length']:
#     print (value)
    k=re.findall(pattern,value)
    if (k):
#         print (k[0])
        emp_length2.append(k[0])
    else:
        emp_length2.append(0)

len(emp_length2)

29018

In [51]:
df['emp_length']=emp_length2

In [52]:
df.to_csv("loan3.csv")